language:
    java

sudo:
    false

jdk:
    - oraclejdk8
    - openjdk7

matrix:
    allow_failures:
        - jdk: oraclejdk8

before_script:
  - git submodule update --remote --recursive

script:
  - cd acceptsuiteservice
  - mvn install -DsdkVersion=0.0.1-SNAPSHOT -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_script:
    deploy.sh